// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AddElement(arg1:number,arg2:string):Promise<engine.Deck>;

export function AddShapeElement(arg1:number,arg2:string):Promise<engine.Deck>;

export function AddSlide(arg1:number):Promise<engine.Deck>;

export function AddSlideWithAI(arg1:string):Promise<engine.Deck>;

export function CanRedo():Promise<boolean>;

export function CanUndo():Promise<boolean>;

export function DeleteElement(arg1:number,arg2:string):Promise<engine.Deck>;

export function DeleteSlide(arg1:number):Promise<engine.Deck>;

export function DuplicateSlide(arg1:number):Promise<engine.Deck>;

export function GenerateDeckWithAI(arg1:string):Promise<engine.Deck>;

export function GetDeck():Promise<engine.Deck>;

export function GetFilePath():Promise<string>;

export function NewDeck():Promise<engine.Deck>;

export function OpenFile():Promise<engine.Deck>;

export function Redo():Promise<engine.Deck>;

export function ReorderSlide(arg1:number,arg2:number):Promise<engine.Deck>;

export function SaveFile():Promise<string>;

export function SaveFileAs():Promise<string>;

export function SetTheme(arg1:engine.Theme):Promise<engine.Deck>;

export function Undo():Promise<engine.Deck>;

export function UpdateDeckMeta(arg1:string,arg2:string):Promise<engine.Deck>;

export function UpdateElement(arg1:number,arg2:engine.Element):Promise<engine.Deck>;

export function UpdateSlideBg(arg1:number,arg2:string):Promise<engine.Deck>;
