// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddElement(arg1, arg2) {
  return window['go']['main']['App']['AddElement'](arg1, arg2);
}

export function AddSlide(arg1) {
  return window['go']['main']['App']['AddSlide'](arg1);
}

export function AddSlideWithAI(arg1) {
  return window['go']['main']['App']['AddSlideWithAI'](arg1);
}

export function CanRedo() {
  return window['go']['main']['App']['CanRedo']();
}

export function CanUndo() {
  return window['go']['main']['App']['CanUndo']();
}

export function DeleteElement(arg1, arg2) {
  return window['go']['main']['App']['DeleteElement'](arg1, arg2);
}

export function DeleteSlide(arg1) {
  return window['go']['main']['App']['DeleteSlide'](arg1);
}

export function DuplicateSlide(arg1) {
  return window['go']['main']['App']['DuplicateSlide'](arg1);
}

export function GenerateDeckWithAI(arg1) {
  return window['go']['main']['App']['GenerateDeckWithAI'](arg1);
}

export function GetDeck() {
  return window['go']['main']['App']['GetDeck']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function NewDeck() {
  return window['go']['main']['App']['NewDeck']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function ReorderSlide(arg1, arg2) {
  return window['go']['main']['App']['ReorderSlide'](arg1, arg2);
}

export function SaveFile() {
  return window['go']['main']['App']['SaveFile']();
}

export function SaveFileAs() {
  return window['go']['main']['App']['SaveFileAs']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateDeckMeta(arg1, arg2) {
  return window['go']['main']['App']['UpdateDeckMeta'](arg1, arg2);
}

export function UpdateElement(arg1, arg2) {
  return window['go']['main']['App']['UpdateElement'](arg1, arg2);
}

export function UpdateSlideBg(arg1, arg2) {
  return window['go']['main']['App']['UpdateSlideBg'](arg1, arg2);
}
